### ISSUE TITLE
numeric greater than failing on reference implementation...

### ISSUE THREAD

**Issue by bcorrie** [airr-community/adc-api#2]
@schristley I am creating some age tests and an age_min >= 6 query fails on the reference implementation (that is, it returns 0 records when there is data that meets that criteria...

See: https://github.com/airr-community/adc-api-tests/commit/fe38cb98ee6a0d46ed98545d834a9853bb0ef0b0

```
$ src/ADCtest.sh https://vdjserver.org/airr/v1 repertoire -v repertoire/pass-field-age-gt-min.json

Running test repertoire/pass-field-age-gt-min.json
WARNING: No gold expectation for pass-field-age-gt-min.json
INFO: Received 0 Repertoires from query
PASS: Query file repertoire/pass-field-age-gt-min.json to https://vdjserver.org/airr/v1/repertoire OK

SUMMARY: All tests passed!!!
```
With
```
$ curl -s --data "{}" https://vdjserver.org/airr/v1/repertoire | python -m json.tool | egrep "age_min|age_max" | grep " 6,"
                "age_min": 6,
                "age_max": 6,
                "age_min": 6,
                "age_max": 6,
                "age_min": 6,
                "age_min": 6,
                "age_min": 6,
                "age_min": 6,
                "age_min": 6,
                "age_min": 6,
```

**Comment by schristley** [comment]
Thanks, that is actually a VDJServer ADC API bug, versus the reference implementation, I'll take a look though. I haven't updated the [test dataset](https://github.com/airr-community/adc-api-tests/blob/master/datasets/florian/florian.airr.yaml) with the new age fields yet.

**Comment by schristley** [comment]
I've updated the test dataset for the new age fields and added a few tests. I added a little bit of variability for age in the test dataset but you might want to add more special cases.
